# MiniPanel Agent 配置文件
server:
  url: "http://localhost:8080"  # 服务器地址
  timeout: 30                   # 请求超时时间（秒）
  retry_count: 3                # 重试次数
  retry_interval: 5             # 重试间隔（秒）

agent:
  node_id: ""                   # 节点ID，留空则自动生成
  node_name: ""                 # 节点名称，留空则使用主机名
  
collector:
  interval: 30                  # 数据采集间隔（秒）
  enable_cpu: true              # 启用CPU监控
  enable_memory: true           # 启用内存监控
  enable_temperature: true      # 启用温度监控
  
# 日志配置
log:
  level: "info"                 # 日志级别: debug, info, warn, error
  file: "./logs/agent.log"      # 日志文件路径
  max_size: 50                  # 日志文件最大大小（MB）
  max_backups: 3                # 保留的日志文件数量
  max_age: 7                    # 日志文件保留天数